import * as dotenv from 'dotenv';
import { DataSource } from 'typeorm';
import { Policy } from '../policies/policy.entity';

dotenv.config();

async function bootstrap() {
  const dataSource = new DataSource({
    type: 'mysql',
    host: process.env.DB_HOST || 'localhost',
    port: Number(process.env.DB_PORT) || 3306,
    username: process.env.DB_USERNAME || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_DATABASE || 'opc',
    entities: [Policy],
    synchronize: false,
  });

  await dataSource.initialize();
  const policyRepository = dataSource.getRepository(Policy);

  const policies = [
    {
      id: 'opc-001',
      title: '人工智能一人公司（OPC）创业补贴申请指南',
      regionName: '广东省',
      lat: 23.1291,
      lng: 113.2644,
      policyType: '补贴',
      targetAudience: '人工智能创业者、超级个体',
      summary: '符合条件的 OPC 创业者可申请最高 10 万元的一次性创业补贴，包括算力补贴、场地补贴等。',
      requirements: '1. 在本地登记注册的人工智能领域一人公司\n2. 公司成立时间不超过 2 年\n3. 主要从事 AI 应用开发、AI 内容创作等业务',
      materials: JSON.stringify([
        { name: '营业执照副本', required: true },
        { name: '法人身份证复印件', required: true },
        { name: 'AI 项目商业计划书', required: true },
      ]),
      officialUrl: 'https://dgi.gd.gov.cn/attachment/0/560/560799/4304326.pdf',
      deadline: '2026-12-31',
      publishedOn: '2025-01-01',
      sourceName: '广东省人工智能产业协会',
      isFeatured: true,
      tags: ['OPC', '人工智能', '创业补贴', '算力补贴'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-002',
      title: 'OPC 算力券申领和使用管理办法',
      regionName: '北京市',
      lat: 39.9042,
      lng: 116.4074,
      policyType: '补贴',
      targetAudience: 'AI 一人公司、独立开发者',
      summary: '为 OPC 创业者提供算力券支持，每年最高 5 万元，用于购买云计算、AI 训练等服务。',
      requirements: '1. 注册地在北京市的一人公司\n2. 主营业务为人工智能相关\n3. 上年度营业收入不超过 100 万元',
      materials: JSON.stringify([
        { name: '算力券申请表', required: true },
        { name: '营业执照', required: true },
        { name: '云服务采购合同', required: false },
      ]),
      officialUrl: 'https://kw.beijing.gov.cn/art/2025/1/15/art_1638_556789.html',
      deadline: '2026-12-31',
      publishedOn: '2025-01-15',
      sourceName: '北京市科委',
      isFeatured: true,
      tags: ['OPC', '算力券', '云计算', 'AI 训练'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-003',
      title: '一人公司 AI 产品开发资助计划',
      regionName: '上海市',
      lat: 31.2304,
      lng: 121.4737,
      policyType: '创业支持',
      targetAudience: 'AI 产品开发者、独立创作者',
      summary: '支持 OPC 开发者开发 AI 原生应用，单个项目最高资助 50 万元。',
      requirements: '1. 项目负责人为唯一创始人\n2. 项目具有创新性和市场前景\n3. 已完成产品原型开发',
      materials: JSON.stringify([
        { name: '项目申报书', required: true },
        { name: '产品 demo 或原型', required: true },
        { name: '市场推广计划', required: true },
      ]),
      officialUrl: 'https://stcsm.sh.gov.cn/nw2/nw2314/nw32419/nw23222/nw42427/u8ai123456.html',
      deadline: '2026-06-30',
      publishedOn: '2025-02-01',
      sourceName: '上海市经济和信息化委员会',
      isFeatured: true,
      tags: ['OPC', 'AI 产品', '开发资助', '独立开发者'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-004',
      title: 'OPC 创作者数据资源开放计划',
      regionName: '浙江省',
      lat: 30.2741,
      lng: 120.1551,
      policyType: '其他',
      targetAudience: 'AI 内容创作者、数据科学家',
      summary: '向 OPC 创作者开放公共数据资源，提供免费数据 API 接口和数据处理工具。',
      requirements: '1. 在浙江省注册的 OPC 或个体工商户\n2. 从事 AI 内容创作、数据分析等业务\n3. 承诺合规使用数据',
      materials: JSON.stringify([
        { name: '数据使用申请表', required: true },
        { name: '数据安全承诺书', required: true },
      ]),
      officialUrl: 'https://data.zjzwfw.gov.cn/jdop_front/channeldetail.do?ch_id=7',
      deadline: '2026-12-31',
      publishedOn: '2025-02-15',
      sourceName: '浙江省大数据发展管理局',
      isFeatured: false,
      tags: ['OPC', '数据开放', 'API', 'AI 创作'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-005',
      title: '超级个体创业贷款贴息政策',
      regionName: '深圳市',
      lat: 22.5431,
      lng: 114.0579,
      policyType: '贷款支持',
      targetAudience: 'AI 领域一人公司创业者',
      summary: '为 OPC 创业者提供创业担保贷款贴息，个人贷款最高 30 万元，全额贴息。',
      requirements: '1. 深圳户籍或在深缴纳社保满 1 年\n2. 注册一人公司且持股不低于 51%\n3. 无不良信用记录',
      materials: JSON.stringify([
        { name: '贷款申请书', required: true },
        { name: '营业执照', required: true },
        { name: '创业计划书', required: true },
      ]),
      officialUrl: 'http://hrss.sz.gov.cn/zwgk/zfxxgk/zfwj/content/post_10294567.html',
      deadline: '2026-12-31',
      publishedOn: '2025-03-01',
      sourceName: '深圳市人力资源和社会保障局',
      isFeatured: true,
      tags: ['OPC', '创业贷款', '贴息', '超级个体'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-006',
      title: 'AI 一人公司税收优惠政策',
      regionName: '海南省',
      lat: 20.0444,
      lng: 110.1999,
      policyType: '税收优惠',
      targetAudience: '海南自贸港 OPC 企业',
      summary: '在海南自贸港注册的 OPC 企业，企业所得税实际税负超过 15% 的部分予以免征。',
      requirements: '1. 在海南自贸港注册并实质运营\n2. 属于鼓励类产业目录中的人工智能领域\n3. 从业人员在海南缴纳社保',
      materials: JSON.stringify([
        { name: '企业所得税申报表', required: true },
        { name: '从业人员社保缴纳证明', required: true },
      ]),
      officialUrl: 'https://www.hainan.gov.cn/hainan/562/563/202501/t20250115_3326789.html',
      deadline: '2026-12-31',
      publishedOn: '2025-03-15',
      sourceName: '海南省税务局',
      isFeatured: true,
      tags: ['OPC', '税收优惠', '自贸港', '企业所得税'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-007',
      title: 'OPC 创业者人才公寓配租办法',
      regionName: '杭州市',
      lat: 30.2741,
      lng: 120.1551,
      policyType: '其他',
      targetAudience: '来杭创业的人工智能人才',
      summary: '为来杭创业的 OPC 创业者提供人才公寓，3 年内租金减免 50%。',
      requirements: '1. 年龄 45 周岁以下\n2. 在杭州市创办人工智能领域企业\n3. 企业成立不超过 3 年',
      materials: JSON.stringify([
        { name: '人才认定申请表', required: true },
        { name: '学历证书或职称证明', required: true },
        { name: '营业执照', required: true },
      ]),
      officialUrl: 'https://rlszj.hangzhou.gov.cn/art/2025/3/20/art_1229432567.html',
      deadline: '2026-12-31',
      publishedOn: '2025-04-01',
      sourceName: '杭州市人才管理服务中心',
      isFeatured: false,
      tags: ['OPC', '人才公寓', '租金减免', '创业支持'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-008',
      title: '一人公司场景应用对接服务',
      regionName: '成都市',
      lat: 30.5728,
      lng: 104.0668,
      policyType: '创业支持',
      targetAudience: 'AI 技术应用型 OPC 企业',
      summary: '为 OPC 企业对接政府、国企应用场景需求，提供项目对接、技术验证等支持。',
      requirements: '1. 注册在成都市的 AI 领域一人公司\n2. 产品或服务具有场景应用价值\n3. 有成功案例或技术储备',
      materials: JSON.stringify([
        { name: '场景应用申报表', required: true },
        { name: '技术方案', required: true },
        { name: '案例介绍', required: false },
      ]),
      officialUrl: 'http://gk.chengdu.gov.cn/govInfoCatalogList.action?deptId=60012',
      deadline: '2026-12-31',
      publishedOn: '2025-04-15',
      sourceName: '成都市新经济发展委员会',
      isFeatured: false,
      tags: ['OPC', '场景应用', '项目对接', '技术验证'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-009',
      title: 'OPC 知识产权保护绿色通道',
      regionName: '国家知识产权局',
      lat: 39.9042,
      lng: 116.4074,
      policyType: '其他',
      targetAudience: '全国 OPC 创业者',
      summary: '为 OPC 创业者提供专利、商标快速审查通道，审查周期缩短 50%。',
      requirements: '1. 申请人为一人公司法定代表人\n2. 申请内容与 AI 技术相关\n3. 承诺申请内容真实有效',
      materials: JSON.stringify([
        { name: '专利/商标申请表', required: true },
        { name: 'OPC 身份证明', required: true },
        { name: '技术交底书', required: true },
      ]),
      officialUrl: 'https://www.cnipa.gov.cn/art/2025/4/1/art_123_178456.html',
      deadline: '2026-12-31',
      publishedOn: '2025-05-01',
      sourceName: '国家知识产权局',
      isFeatured: false,
      tags: ['OPC', '知识产权', '专利快速审查', '商标'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'opc-010',
      title: 'AI 超级个体孵化基地入驻计划',
      regionName: '苏州市',
      lat: 31.2989,
      lng: 120.5853,
      policyType: '创业支持',
      targetAudience: '初创期 AI 一人公司',
      summary: '提供免租办公空间、共享会议室、直播设备等，最长可入驻 2 年。',
      requirements: '1. AI 领域一人公司或拟创业个人\n2. 团队人数不超过 5 人\n3. 承诺参加孵化培训活动',
      materials: JSON.stringify([
        { name: '入驻申请表', required: true },
        { name: '商业计划书', required: true },
        { name: '团队介绍', required: true },
      ]),
      officialUrl: 'http://www.suzhou.gov.cn/szsrmzf/565/202505/52894326.shtml',
      deadline: '2026-12-31',
      publishedOn: '2025-05-15',
      sourceName: '苏州市科技局',
      isFeatured: true,
      tags: ['OPC', '孵化基地', '免租办公', '共享空间'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  try {
    for (const policyData of policies) {
      await policyRepository.upsert(policyData, ['id']);
      console.log(`Inserted policy: ${policyData.title}`);
    }
    console.log('\nAll OPC policies seeded successfully!');
    console.log(`Total: ${policies.length} policies inserted.`);
  } catch (error) {
    console.error('Error seeding policies:', error);
  }

  await dataSource.destroy();
}

bootstrap();
